version: "3.7"

services:

  postgres10:
    platform: linux/amd64
    image: postgres:10
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5430:5432

  postgres11:
    platform: linux/amd64
    image: postgres:11
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5431:5432

  postgres12:
    platform: linux/amd64
    image: postgres:12
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5432:5432

  postgres13:
    platform: linux/amd64
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5433:5432

  postgres14:
    platform: linux/amd64
    image: postgres:14
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5434:5432

