// Code generated by ent, DO NOT EDIT.

package organizationalunittype

const (
	// Label holds the string label denoting the organizationalunittype type in the database.
	Label = "organizational_unit_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeOrganizationalUnits holds the string denoting the organizational_units edge name in mutations.
	EdgeOrganizationalUnits = "organizational_units"
	// Table holds the table name of the organizationalunittype in the database.
	Table = "organizational_unit_types"
	// OrganizationalUnitsTable is the table that holds the organizational_units relation/edge.
	OrganizationalUnitsTable = "organizational_units"
	// OrganizationalUnitsInverseTable is the table name for the OrganizationalUnit entity.
	// It exists in this package in order to avoid circular dependency with the "organizationalunit" package.
	OrganizationalUnitsInverseTable = "organizational_units"
	// OrganizationalUnitsColumn is the table column denoting the organizational_units relation/edge.
	OrganizationalUnitsColumn = "type_id"
)

// Columns holds all SQL columns for organizationalunittype fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
