// Code generated by ent, DO NOT EDIT.

package specialty

const (
	// Label holds the string label denoting the specialty type in the database.
	Label = "specialty"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeOrganizationalUnits holds the string denoting the organizational_units edge name in mutations.
	EdgeOrganizationalUnits = "organizational_units"
	// Table holds the table name of the specialty in the database.
	Table = "specialties"
	// OrganizationalUnitsTable is the table that holds the organizational_units relation/edge. The primary key declared below.
	OrganizationalUnitsTable = "organizational_unit_specialties"
	// OrganizationalUnitsInverseTable is the table name for the OrganizationalUnit entity.
	// It exists in this package in order to avoid circular dependency with the "organizationalunit" package.
	OrganizationalUnitsInverseTable = "organizational_units"
)

// Columns holds all SQL columns for specialty fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// OrganizationalUnitsPrimaryKey and OrganizationalUnitsColumn2 are the table columns denoting the
	// primary key for the organizational_units relation (M2M).
	OrganizationalUnitsPrimaryKey = []string{"organizational_unit_id", "specialty_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
