// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/ent/organizationalunittype"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrganizationalUnitTypeDelete is the builder for deleting a OrganizationalUnitType entity.
type OrganizationalUnitTypeDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationalUnitTypeMutation
}

// Where appends a list predicates to the OrganizationalUnitTypeDelete builder.
func (outd *OrganizationalUnitTypeDelete) Where(ps ...predicate.OrganizationalUnitType) *OrganizationalUnitTypeDelete {
	outd.mutation.Where(ps...)
	return outd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (outd *OrganizationalUnitTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(outd.hooks) == 0 {
		affected, err = outd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrganizationalUnitTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			outd.mutation = mutation
			affected, err = outd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(outd.hooks) - 1; i >= 0; i-- {
			if outd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = outd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, outd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (outd *OrganizationalUnitTypeDelete) ExecX(ctx context.Context) int {
	n, err := outd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (outd *OrganizationalUnitTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: organizationalunittype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: organizationalunittype.FieldID,
			},
		},
	}
	if ps := outd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, outd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// OrganizationalUnitTypeDeleteOne is the builder for deleting a single OrganizationalUnitType entity.
type OrganizationalUnitTypeDeleteOne struct {
	outd *OrganizationalUnitTypeDelete
}

// Exec executes the deletion query.
func (outdo *OrganizationalUnitTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := outdo.outd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationalunittype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (outdo *OrganizationalUnitTypeDeleteOne) ExecX(ctx context.Context) {
	outdo.outd.ExecX(ctx)
}
