// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"entgo.io/bug/ent/organizationalunit"
	"entgo.io/bug/ent/organizationalunittype"
	"entgo.io/bug/ent/schema"
	"entgo.io/bug/ent/specialty"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	organizationalunitFields := schema.OrganizationalUnit{}.Fields()
	_ = organizationalunitFields
	// organizationalunitDescDisplayName is the schema descriptor for display_name field.
	organizationalunitDescDisplayName := organizationalunitFields[1].Descriptor()
	// organizationalunit.DefaultDisplayName holds the default value on creation for the display_name field.
	organizationalunit.DefaultDisplayName = organizationalunitDescDisplayName.Default.(string)
	// organizationalunitDescCreatedAt is the schema descriptor for created_at field.
	organizationalunitDescCreatedAt := organizationalunitFields[2].Descriptor()
	// organizationalunit.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationalunit.DefaultCreatedAt = organizationalunitDescCreatedAt.Default.(func() time.Time)
	// organizationalunitDescMetadata is the schema descriptor for metadata field.
	organizationalunitDescMetadata := organizationalunitFields[5].Descriptor()
	// organizationalunit.DefaultMetadata holds the default value on creation for the metadata field.
	organizationalunit.DefaultMetadata = organizationalunitDescMetadata.Default.([]string)
	// organizationalunitDescID is the schema descriptor for id field.
	organizationalunitDescID := organizationalunitFields[0].Descriptor()
	// organizationalunit.DefaultID holds the default value on creation for the id field.
	organizationalunit.DefaultID = organizationalunitDescID.Default.(string)
	// organizationalunit.IDValidator is a validator for the "id" field. It is called by the builders before save.
	organizationalunit.IDValidator = organizationalunitDescID.Validators[0].(func(string) error)
	organizationalunittypeFields := schema.OrganizationalUnitType{}.Fields()
	_ = organizationalunittypeFields
	// organizationalunittypeDescID is the schema descriptor for id field.
	organizationalunittypeDescID := organizationalunittypeFields[0].Descriptor()
	// organizationalunittype.DefaultID holds the default value on creation for the id field.
	organizationalunittype.DefaultID = organizationalunittypeDescID.Default.(string)
	// organizationalunittype.IDValidator is a validator for the "id" field. It is called by the builders before save.
	organizationalunittype.IDValidator = organizationalunittypeDescID.Validators[0].(func(string) error)
	specialtyFields := schema.Specialty{}.Fields()
	_ = specialtyFields
	// specialtyDescID is the schema descriptor for id field.
	specialtyDescID := specialtyFields[0].Descriptor()
	// specialty.DefaultID holds the default value on creation for the id field.
	specialty.DefaultID = specialtyDescID.Default.(string)
	// specialty.IDValidator is a validator for the "id" field. It is called by the builders before save.
	specialty.IDValidator = specialtyDescID.Validators[0].(func(string) error)
}
