// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/bug/ent/organizationalunit"
	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/specialty"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpecialtyUpdate is the builder for updating Specialty entities.
type SpecialtyUpdate struct {
	config
	hooks    []Hook
	mutation *SpecialtyMutation
}

// Where appends a list predicates to the SpecialtyUpdate builder.
func (su *SpecialtyUpdate) Where(ps ...predicate.Specialty) *SpecialtyUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SpecialtyUpdate) SetName(s string) *SpecialtyUpdate {
	su.mutation.SetName(s)
	return su
}

// AddOrganizationalUnitIDs adds the "organizational_units" edge to the OrganizationalUnit entity by IDs.
func (su *SpecialtyUpdate) AddOrganizationalUnitIDs(ids ...string) *SpecialtyUpdate {
	su.mutation.AddOrganizationalUnitIDs(ids...)
	return su
}

// AddOrganizationalUnits adds the "organizational_units" edges to the OrganizationalUnit entity.
func (su *SpecialtyUpdate) AddOrganizationalUnits(o ...*OrganizationalUnit) *SpecialtyUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return su.AddOrganizationalUnitIDs(ids...)
}

// Mutation returns the SpecialtyMutation object of the builder.
func (su *SpecialtyUpdate) Mutation() *SpecialtyMutation {
	return su.mutation
}

// ClearOrganizationalUnits clears all "organizational_units" edges to the OrganizationalUnit entity.
func (su *SpecialtyUpdate) ClearOrganizationalUnits() *SpecialtyUpdate {
	su.mutation.ClearOrganizationalUnits()
	return su
}

// RemoveOrganizationalUnitIDs removes the "organizational_units" edge to OrganizationalUnit entities by IDs.
func (su *SpecialtyUpdate) RemoveOrganizationalUnitIDs(ids ...string) *SpecialtyUpdate {
	su.mutation.RemoveOrganizationalUnitIDs(ids...)
	return su
}

// RemoveOrganizationalUnits removes "organizational_units" edges to OrganizationalUnit entities.
func (su *SpecialtyUpdate) RemoveOrganizationalUnits(o ...*OrganizationalUnit) *SpecialtyUpdate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return su.RemoveOrganizationalUnitIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SpecialtyUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecialtyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpecialtyUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpecialtyUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpecialtyUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SpecialtyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specialty.Table,
			Columns: specialty.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: specialty.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specialty.FieldName,
		})
	}
	if su.mutation.OrganizationalUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedOrganizationalUnitsIDs(); len(nodes) > 0 && !su.mutation.OrganizationalUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.OrganizationalUnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specialty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SpecialtyUpdateOne is the builder for updating a single Specialty entity.
type SpecialtyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpecialtyMutation
}

// SetName sets the "name" field.
func (suo *SpecialtyUpdateOne) SetName(s string) *SpecialtyUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// AddOrganizationalUnitIDs adds the "organizational_units" edge to the OrganizationalUnit entity by IDs.
func (suo *SpecialtyUpdateOne) AddOrganizationalUnitIDs(ids ...string) *SpecialtyUpdateOne {
	suo.mutation.AddOrganizationalUnitIDs(ids...)
	return suo
}

// AddOrganizationalUnits adds the "organizational_units" edges to the OrganizationalUnit entity.
func (suo *SpecialtyUpdateOne) AddOrganizationalUnits(o ...*OrganizationalUnit) *SpecialtyUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return suo.AddOrganizationalUnitIDs(ids...)
}

// Mutation returns the SpecialtyMutation object of the builder.
func (suo *SpecialtyUpdateOne) Mutation() *SpecialtyMutation {
	return suo.mutation
}

// ClearOrganizationalUnits clears all "organizational_units" edges to the OrganizationalUnit entity.
func (suo *SpecialtyUpdateOne) ClearOrganizationalUnits() *SpecialtyUpdateOne {
	suo.mutation.ClearOrganizationalUnits()
	return suo
}

// RemoveOrganizationalUnitIDs removes the "organizational_units" edge to OrganizationalUnit entities by IDs.
func (suo *SpecialtyUpdateOne) RemoveOrganizationalUnitIDs(ids ...string) *SpecialtyUpdateOne {
	suo.mutation.RemoveOrganizationalUnitIDs(ids...)
	return suo
}

// RemoveOrganizationalUnits removes "organizational_units" edges to OrganizationalUnit entities.
func (suo *SpecialtyUpdateOne) RemoveOrganizationalUnits(o ...*OrganizationalUnit) *SpecialtyUpdateOne {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return suo.RemoveOrganizationalUnitIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SpecialtyUpdateOne) Select(field string, fields ...string) *SpecialtyUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Specialty entity.
func (suo *SpecialtyUpdateOne) Save(ctx context.Context) (*Specialty, error) {
	var (
		err  error
		node *Specialty
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecialtyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Specialty)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SpecialtyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpecialtyUpdateOne) SaveX(ctx context.Context) *Specialty {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SpecialtyUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpecialtyUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SpecialtyUpdateOne) sqlSave(ctx context.Context) (_node *Specialty, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specialty.Table,
			Columns: specialty.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: specialty.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Specialty.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, specialty.FieldID)
		for _, f := range fields {
			if !specialty.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != specialty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specialty.FieldName,
		})
	}
	if suo.mutation.OrganizationalUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedOrganizationalUnitsIDs(); len(nodes) > 0 && !suo.mutation.OrganizationalUnitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.OrganizationalUnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Specialty{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specialty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
