// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/bug/ent/organizationalunit"
	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/specialty"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpecialtyQuery is the builder for querying Specialty entities.
type SpecialtyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Specialty
	// eager-loading edges.
	withOrganizationalUnits *OrganizationalUnitQuery
	modifiers               []func(*sql.Selector)
	loadTotal               []func(context.Context, []*Specialty) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SpecialtyQuery builder.
func (sq *SpecialtyQuery) Where(ps ...predicate.Specialty) *SpecialtyQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit adds a limit step to the query.
func (sq *SpecialtyQuery) Limit(limit int) *SpecialtyQuery {
	sq.limit = &limit
	return sq
}

// Offset adds an offset step to the query.
func (sq *SpecialtyQuery) Offset(offset int) *SpecialtyQuery {
	sq.offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SpecialtyQuery) Unique(unique bool) *SpecialtyQuery {
	sq.unique = &unique
	return sq
}

// Order adds an order step to the query.
func (sq *SpecialtyQuery) Order(o ...OrderFunc) *SpecialtyQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryOrganizationalUnits chains the current query on the "organizational_units" edge.
func (sq *SpecialtyQuery) QueryOrganizationalUnits() *OrganizationalUnitQuery {
	query := &OrganizationalUnitQuery{config: sq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(specialty.Table, specialty.FieldID, selector),
			sqlgraph.To(organizationalunit.Table, organizationalunit.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, specialty.OrganizationalUnitsTable, specialty.OrganizationalUnitsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Specialty entity from the query.
// Returns a *NotFoundError when no Specialty was found.
func (sq *SpecialtyQuery) First(ctx context.Context) (*Specialty, error) {
	nodes, err := sq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{specialty.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SpecialtyQuery) FirstX(ctx context.Context) *Specialty {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Specialty ID from the query.
// Returns a *NotFoundError when no Specialty ID was found.
func (sq *SpecialtyQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{specialty.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SpecialtyQuery) FirstIDX(ctx context.Context) string {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Specialty entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Specialty entity is found.
// Returns a *NotFoundError when no Specialty entities are found.
func (sq *SpecialtyQuery) Only(ctx context.Context) (*Specialty, error) {
	nodes, err := sq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{specialty.Label}
	default:
		return nil, &NotSingularError{specialty.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SpecialtyQuery) OnlyX(ctx context.Context) *Specialty {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Specialty ID in the query.
// Returns a *NotSingularError when more than one Specialty ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SpecialtyQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{specialty.Label}
	default:
		err = &NotSingularError{specialty.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SpecialtyQuery) OnlyIDX(ctx context.Context) string {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Specialties.
func (sq *SpecialtyQuery) All(ctx context.Context) ([]*Specialty, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sq *SpecialtyQuery) AllX(ctx context.Context) []*Specialty {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Specialty IDs.
func (sq *SpecialtyQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := sq.Select(specialty.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SpecialtyQuery) IDsX(ctx context.Context) []string {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SpecialtyQuery) Count(ctx context.Context) (int, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SpecialtyQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SpecialtyQuery) Exist(ctx context.Context) (bool, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SpecialtyQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SpecialtyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SpecialtyQuery) Clone() *SpecialtyQuery {
	if sq == nil {
		return nil
	}
	return &SpecialtyQuery{
		config:                  sq.config,
		limit:                   sq.limit,
		offset:                  sq.offset,
		order:                   append([]OrderFunc{}, sq.order...),
		predicates:              append([]predicate.Specialty{}, sq.predicates...),
		withOrganizationalUnits: sq.withOrganizationalUnits.Clone(),
		// clone intermediate query.
		sql:    sq.sql.Clone(),
		path:   sq.path,
		unique: sq.unique,
	}
}

// WithOrganizationalUnits tells the query-builder to eager-load the nodes that are connected to
// the "organizational_units" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SpecialtyQuery) WithOrganizationalUnits(opts ...func(*OrganizationalUnitQuery)) *SpecialtyQuery {
	query := &OrganizationalUnitQuery{config: sq.config}
	for _, opt := range opts {
		opt(query)
	}
	sq.withOrganizationalUnits = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Specialty.Query().
//		GroupBy(specialty.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sq *SpecialtyQuery) GroupBy(field string, fields ...string) *SpecialtyGroupBy {
	grbuild := &SpecialtyGroupBy{config: sq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sq.sqlQuery(ctx), nil
	}
	grbuild.label = specialty.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Specialty.Query().
//		Select(specialty.FieldName).
//		Scan(ctx, &v)
//
func (sq *SpecialtyQuery) Select(fields ...string) *SpecialtySelect {
	sq.fields = append(sq.fields, fields...)
	selbuild := &SpecialtySelect{SpecialtyQuery: sq}
	selbuild.label = specialty.Label
	selbuild.flds, selbuild.scan = &sq.fields, selbuild.Scan
	return selbuild
}

func (sq *SpecialtyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sq.fields {
		if !specialty.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SpecialtyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Specialty, error) {
	var (
		nodes       = []*Specialty{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withOrganizationalUnits != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*Specialty).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &Specialty{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := sq.withOrganizationalUnits; query != nil {
		edgeids := make([]driver.Value, len(nodes))
		byid := make(map[string]*Specialty)
		nids := make(map[string]map[*Specialty]struct{})
		for i, node := range nodes {
			edgeids[i] = node.ID
			byid[node.ID] = node
			node.Edges.OrganizationalUnits = []*OrganizationalUnit{}
		}
		query.Where(func(s *sql.Selector) {
			joinT := sql.Table(specialty.OrganizationalUnitsTable)
			s.Join(joinT).On(s.C(organizationalunit.FieldID), joinT.C(specialty.OrganizationalUnitsPrimaryKey[0]))
			s.Where(sql.InValues(joinT.C(specialty.OrganizationalUnitsPrimaryKey[1]), edgeids...))
			columns := s.SelectedColumns()
			s.Select(joinT.C(specialty.OrganizationalUnitsPrimaryKey[1]))
			s.AppendSelect(columns...)
			s.SetDistinct(false)
		})
		neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]interface{}, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]interface{}{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []interface{}) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*Specialty]struct{}{byid[outValue]: struct{}{}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byid[outValue]] = struct{}{}
				return nil
			}
		})
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "organizational_units" node returned %v`, n.ID)
			}
			for kn := range nodes {
				kn.Edges.OrganizationalUnits = append(kn.Edges.OrganizationalUnits, n)
			}
		}
	}

	for i := range sq.loadTotal {
		if err := sq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SpecialtyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.fields
	if len(sq.fields) > 0 {
		_spec.Unique = sq.unique != nil && *sq.unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SpecialtyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sq *SpecialtyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specialty.Table,
			Columns: specialty.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: specialty.FieldID,
			},
		},
		From:   sq.sql,
		Unique: true,
	}
	if unique := sq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, specialty.FieldID)
		for i := range fields {
			if fields[i] != specialty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SpecialtyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(specialty.Table)
	columns := sq.fields
	if len(columns) == 0 {
		columns = specialty.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.unique != nil && *sq.unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SpecialtyGroupBy is the group-by builder for Specialty entities.
type SpecialtyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SpecialtyGroupBy) Aggregate(fns ...AggregateFunc) *SpecialtyGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sgb *SpecialtyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sgb.path(ctx)
	if err != nil {
		return err
	}
	sgb.sql = query
	return sgb.sqlScan(ctx, v)
}

func (sgb *SpecialtyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sgb.fields {
		if !specialty.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sgb *SpecialtyGroupBy) sqlQuery() *sql.Selector {
	selector := sgb.sql.Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sgb.fields)+len(sgb.fns))
		for _, f := range sgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sgb.fields...)...)
}

// SpecialtySelect is the builder for selecting fields of Specialty entities.
type SpecialtySelect struct {
	*SpecialtyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SpecialtySelect) Scan(ctx context.Context, v interface{}) error {
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	ss.sql = ss.SpecialtyQuery.sqlQuery(ctx)
	return ss.sqlScan(ctx, v)
}

func (ss *SpecialtySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ss.sql.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
