// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/bug/ent/organizationalunit"
	"entgo.io/bug/ent/specialty"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpecialtyCreate is the builder for creating a Specialty entity.
type SpecialtyCreate struct {
	config
	mutation *SpecialtyMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SpecialtyCreate) SetName(s string) *SpecialtyCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetID sets the "id" field.
func (sc *SpecialtyCreate) SetID(s string) *SpecialtyCreate {
	sc.mutation.SetID(s)
	return sc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (sc *SpecialtyCreate) SetNillableID(s *string) *SpecialtyCreate {
	if s != nil {
		sc.SetID(*s)
	}
	return sc
}

// AddOrganizationalUnitIDs adds the "organizational_units" edge to the OrganizationalUnit entity by IDs.
func (sc *SpecialtyCreate) AddOrganizationalUnitIDs(ids ...string) *SpecialtyCreate {
	sc.mutation.AddOrganizationalUnitIDs(ids...)
	return sc
}

// AddOrganizationalUnits adds the "organizational_units" edges to the OrganizationalUnit entity.
func (sc *SpecialtyCreate) AddOrganizationalUnits(o ...*OrganizationalUnit) *SpecialtyCreate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return sc.AddOrganizationalUnitIDs(ids...)
}

// Mutation returns the SpecialtyMutation object of the builder.
func (sc *SpecialtyCreate) Mutation() *SpecialtyMutation {
	return sc.mutation
}

// Save creates the Specialty in the database.
func (sc *SpecialtyCreate) Save(ctx context.Context) (*Specialty, error) {
	var (
		err  error
		node *Specialty
	)
	sc.defaults()
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecialtyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, sc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Specialty)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SpecialtyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SpecialtyCreate) SaveX(ctx context.Context) *Specialty {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SpecialtyCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SpecialtyCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SpecialtyCreate) defaults() {
	if _, ok := sc.mutation.ID(); !ok {
		v := specialty.DefaultID
		sc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SpecialtyCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Specialty.name"`)}
	}
	if v, ok := sc.mutation.ID(); ok {
		if err := specialty.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Specialty.id": %w`, err)}
		}
	}
	return nil
}

func (sc *SpecialtyCreate) sqlSave(ctx context.Context) (*Specialty, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Specialty.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (sc *SpecialtyCreate) createSpec() (*Specialty, *sqlgraph.CreateSpec) {
	var (
		_node = &Specialty{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: specialty.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: specialty.FieldID,
			},
		}
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specialty.FieldName,
		})
		_node.Name = value
	}
	if nodes := sc.mutation.OrganizationalUnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   specialty.OrganizationalUnitsTable,
			Columns: specialty.OrganizationalUnitsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: organizationalunit.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SpecialtyCreateBulk is the builder for creating many Specialty entities in bulk.
type SpecialtyCreateBulk struct {
	config
	builders []*SpecialtyCreate
}

// Save creates the Specialty entities in the database.
func (scb *SpecialtyCreateBulk) Save(ctx context.Context) ([]*Specialty, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Specialty, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpecialtyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SpecialtyCreateBulk) SaveX(ctx context.Context) []*Specialty {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SpecialtyCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SpecialtyCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
