// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OrganizationalUnit is the predicate function for organizationalunit builders.
type OrganizationalUnit func(*sql.Selector)

// OrganizationalUnitType is the predicate function for organizationalunittype builders.
type OrganizationalUnitType func(*sql.Selector)

// Specialty is the predicate function for specialty builders.
type Specialty func(*sql.Selector)
